<a href="https://colab.research.google.com/github/Fabrizioocampo/prueba1/blob/main/Trabajo_Diplo_Cs_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img
     src="https://drive.google.com/uc?export=view&id=1NZbT08OriQQsnd89332TVQ8IuIqfq4aq"
     alt="pypl"
     width=80%
     height=80%>
</p>

En el presente trabajo elegimos trabajar con la Encuesta Permanente de Hogares (EPH, 4° Trim. 2023), es un programa nacional de producción permanente de indicadores sociales cuyo objetivo es conocer las características socioeconómicas de la población.

Nos enfocamos especialmente en el tema de empleabilidad, entendemos que el acceso al empleo, la calidad del trabajo y las desigualdades en el mercado laboral son problemas centrales para las familias y el desarrollo social del país.

La EPH nos permite abordar preguntas clave sobre cómo influyen factores como la educación, el género, la edad, el contexto de residencia y el ingreso en las posibilidades de acceso al trabajo y las diferencias entre grupos sociales.

A través de este trabajo, buscamos:

- Comprender los determinantes de la empleabilidad en el Gran Buenos Aires.
- Identificar desigualdades y brechas en el mercado de trabajo.
- Desarrollar nuestras capacidades como analistas de datos, integrando teoría y práctica, y aprendiendo a razonar y trabajar en equipo ante un desafío real.

##Carga de base de datos

In [1]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
# Cargamos la base de datos
import pandas as pd
from zipfile import ZipFile
import requests
from io import BytesIO
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# URL del archivo ZIP
url_zip = "https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2024_txt.zip"

# Descargar el archivo ZIP
response = requests.get(url_zip)

# Leer el archivo ZIP
with ZipFile(BytesIO(response.content)) as zip_file:
    files = zip_file.namelist()
    print("Archivos en el ZIP:", files)

    # Elegimos el archivo individual
    selected_file = 'usu_individual_T424.txt'

    # Leer el archivo CSV
    with zip_file.open(selected_file) as csv_file:
        df = pd.read_csv(csv_file, sep=";", encoding='latin1')

Archivos en el ZIP: ['usu_hogar_T424.txt', 'usu_individual_T424.txt']

/tmp/ipython-input-27-1861298759.py:26: DtypeWarning: Columns (73,94,102,132,141,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file, sep=";", encoding='latin1')

## Análisis Exploratorio de los datos

In [ ]:
#Veamos las primeras diez filas:
df.head(10)

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,V21_03_M,V22_01_M,V22_02_M,V22_03_M,P_DECCF,P_RDECCF,P_GDECCF,P_PDECCF,P_IDECCF,P_ADECCF
0,TQRMNORTSHJKLMCDEHPJB00872828,2024,4,1,2,1,40,S,29,384,...,0,70000.0,0.0,0.0,8.0,9.0,8.0,NaN,8.0,10.0
1,TQRMNOSRQHJLLNCDEHPJB00872829,2024,4,1,1,1,40,S,29,265,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,TQRMNOSRQHJLLNCDEHPJB00872829,2024,4,1,2,1,40,S,29,265,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,TQRMNOSQTHMKLQCDEHPJB00872830,2024,4,1,1,1,40,S,29,380,...,0,0.0,0.0,0.0,9.0,10.0,9.0,NaN,9.0,10.0
4,TQRMNOSQTHMKLQCDEHPJB00872830,2024,4,1,2,1,40,S,29,380,...,0,0.0,0.0,0.0,9.0,10.0,9.0,NaN,9.0,10.0
5,TQRMNOPYTHLMKOCDEIHJF00854747,2024,4,1,1,1,44,N,31,226,...,0,0.0,0.0,0.0,10.0,9.0,NaN,10.0,10.0,9.0
6,TQRMNOPYTHLMKOCDEIHJF00854747,2024,4,1,2,1,44,N,31,226,...,0,0.0,0.0,0.0,10.0,9.0,NaN,10.0,10.0,9.0
7,TQRMNOPYTHLMKOCDEIHJF00854747,2024,4,1,3,1,44,N,31,226,...,0,0.0,0.0,0.0,10.0,9.0,NaN,10.0,10.0,9.0
8,TQRMNOPYTHLMKOCDEIHJF00854747,2024,4,1,4,1,44,N,31,226,...,0,0.0,0.0,0.0,10.0,9.0,NaN,10.0,10.0,9.0
9,TQRMNOPYTHLMKOCDEIHJF00854747,2024,4,1,5,0,44,N,31,226,...,0,0.0,0.0,0.0,10.0,9.0,NaN,10.0,10.0,9.0

In [ ]:
#Veamos algunas observaciones:
df.sample(10)

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,V21_03_M,V22_01_M,V22_02_M,V22_03_M,P_DECCF,P_RDECCF,P_GDECCF,P_PDECCF,P_IDECCF,P_ADECCF
31124,TQRMNOQTPHKMKMCDEGKDB00872221,2024,4,1,3,1,43,N,14,113,...,0,0.0,0.0,0.0,5.0,4.0,NaN,5.0,5.0,6.0
45456,TQSMNOPXPHKNKSCDEGGFB00877578,2024,4,1,1,1,42,S,10,741,...,0,0.0,0.0,0.0,2.0,2.0,2.0,NaN,2.0,2.0
21940,TQRMNOQUWHLMKQCDEFJAH00851663,2024,4,1,2,1,43,N,3,285,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
42362,TQRMNOSUPHJOKNCDEGNFJ00877407,2024,4,1,1,1,44,N,17,315,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
29391,TQRMNOSURHMOLLCDEHPJB00811520,2024,4,1,2,1,40,S,29,429,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8496,TQRMNOQRTHJMLMCDEIOAH00873375,2024,4,1,2,1,43,N,38,87,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
24923,TQRMNORTSHLNLMCDEIMBF00855873,2024,4,1,2,1,43,N,36,103,...,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
931,TQRMNOPWVHJOKMCDEGJBF00872538,2024,4,1,1,1,43,S,13,1057,...,0,0.0,0.0,70000.0,5.0,4.0,5.0,NaN,5.0,4.0
23091,TQRMNOSRYHJOLPCDEHLEH00874883,2024,4,1,1,1,40,N,25,214,...,0,0.0,0.0,0.0,2.0,2.0,NaN,2.0,2.0,2.0
34576,TQRMNOPPTHKMKPCDEOHCH00876293,2024,4,1,3,1,44,N,91,171,...,0,0.0,0.0,0.0,8.0,7.0,NaN,9.0,8.0,7.0

In [ ]:
#Vemos el nombre de las variables y su tipo, asi como la dimensión del data frame:
from re import VERBOSE
df.info(verbose=True)
# El dataframe cuenta con 46860 registros y 235 columnas, de las cuales float64 (166), int64(59), object(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46860 entries, 0 to 46859
Data columns (total 235 columns):
 #    Column      Dtype
---   ------      -----
 0    CODUSU      object
 1    ANO4        int64
 2    TRIMESTRE   int64
 3    NRO_HOGAR   int64
 4    COMPONENTE  int64
 5    H15         int64
 6    REGION      int64
 7    MAS_500     object
 8    AGLOMERADO  int64
 9    PONDERA     int64
 10   CH03        int64
 11   CH04        int64
 12   CH05        int64
 13   CH06        int64
 14   CH07        int64
 15   CH08        int64
 16   CH09        int64
 17   CH10        int64
 18   CH11        int64
 19   CH12        int64
 20   CH13        int64
 21   CH14        float64
 22   CH15        int64
 23   CH15_COD    float64
 24   CH16        int64
 25   CH16_COD    float64
 26   NIVEL_ED    int64
 27   ESTADO      int64
 28   CAT_OCUP    int64
 29   CAT_INAC    int64
 30   IMPUTA      float64
 31   PP02C1      int64
 32   PP02C2      int64
 33   PP02C3      int64
 34   PP02C4      int64
 35   PP02C5      int64
 36   PP02C6      int64
 37   PP02C7      int64
 38   PP02C8      int64
 39   PP02E       int64
 40   PP02H       int64
 41   PP02I       int64
 42   PP03C       float64
 43   PP03D       float64
 44   PP3E_TOT    float64
 45   PP3F_TOT    float64
 46   PP03G       float64
 47   PP03H       float64
 48   PP03I       float64
 49   PP03J       float64
 50   INTENSI     float64
 51   PP04A       float64
 52   PP04B_COD   float64
 53   PP04B1      float64
 54   PP04B2      float64
 55   PP04B3_MES  float64
 56   PP04B3_ANO  float64
 57   PP04B3_DIA  float64
 58   PP04C       float64
 59   PP04C99     float64
 60   PP04D_COD   float64
 61   PP04G       float64
 62   PP05B2_MES  float64
 63   PP05B2_ANO  float64
 64   PP05B2_DIA  float64
 65   PP05C_1     float64
 66   PP05C_2     float64
 67   PP05C_3     float64
 68   PP05E       float64
 69   PP05F       float64
 70   PP05H       float64
 71   PP06A       float64
 72   PP06C       float64
 73   PP06D       object
 74   PP06E       float64
 75   PP06H       float64
 76   PP07A       float64
 77   PP07C       float64
 78   PP07D       float64
 79   PP07E       float64
 80   PP07F1      float64
 81   PP07F2      float64
 82   PP07F3      float64
 83   PP07F4      float64
 84   PP07F5      float64
 85   PP07G1      float64
 86   PP07G2      float64
 87   PP07G3      float64
 88   PP07G4      float64
 89   PP07G_59    float64
 90   PP07H       float64
 91   PP07I       float64
 92   PP07J       float64
 93   PP07K       float64
 94   PP08D1      object
 95   PP08D4      float64
 96   PP08F1      float64
 97   PP08F2      float64
 98   PP08J1      float64
 99   PP08J2      float64
 100  PP08J3      float64
 101  PP09A       float64
 102  PP09A_ESP   object
 103  PP09B       float64
 104  PP09C       float64
 105  PP09C_ESP   object
 106  PP10A       float64
 107  PP10C       float64
 108  PP10D       float64
 109  PP10E       float64
 110  PP11A       float64
 111  PP11B_COD   float64
 112  PP11B1      float64
 113  PP11B2_MES  float64
 114  PP11B2_ANO  float64
 115  PP11B2_DIA  float64
 116  PP11C       float64
 117  PP11C99     float64
 118  PP11D_COD   float64
 119  PP11G_ANO   float64
 120  PP11G_MES   float64
 121  PP11G_DIA   float64
 122  PP11L       float64
 123  PP11L1      float64
 124  PP11M       float64
 125  PP11N       float64
 126  PP11O       float64
 127  PP11P       float64
 128  PP11Q       float64
 129  PP11R       float64
 130  PP11S       float64
 131  PP11T       float64
 132  P21         object
 133  DECOCUR     int64
 134  IDECOCUR    float64
 135  RDECOCUR    int64
 136  GDECOCUR    float64
 137  PDECOCUR    float64
 138  ADECOCUR    int64
 139  PONDIIO     int64
 140  TOT_P12     float64
 141  P47T        object
 142  DECINDR     int64
 143  IDECINDR    float64
 144  RDECINDR    int64
 145  GDECINDR    float64
 146  PDECINDR    float64
 147  ADECINDR    int64
 148  PONDII      int64
 149  V3_M        float64
 150  V4_M        float64
 151  V8_M        float64
 152  V9_M        float64
 153  V10_M       float64
 154  V12_M       float64
 155  V18_M       float64
 156  V19_AM      int64
 157  T_VI        float64
 158  ITF         object
 159  DECIFR      int64
 160  IDECIFR     float64
 161  RDECIFR     int64
 162  GDECIFR     float64
 163  PDECIFR     float64
 164  ADECIFR     int64
 165  IPCF        object
 166  DECCFR      int64
 167  IDECCFR     float64
 168  RDECCFR     int64
 169  GDECCFR     float64
 170  PDECCFR     float64
 171  ADECCFR     int64
 172  PONDIH      int64
 173  V2_02_M     float64
 174  V2_03_M     float64
 175  V5_03_M     float64
 176  V11_02_M    float64
 177  PP07B1_01   float64
 178  EMPLEO      float64
 179  SECTOR      float64
 180  PP02A       int64
 181  PP02B       int64
 182  PP02D       int64
 183  PP02F       int64
 184  PP02G       int64
 185  PP03K       float64
 186  PP04A1      float64
 187  PP05B3      float64
 188  PP05I       float64
 189  PP05J       float64
 190  PP05K       float64
 191  PP06E1      float64
 192  PP06K       float64
 193  PP06K_SEM   float64
 194  PP06K_MES   float64
 195  PP06L       float64
 196  PP07F1_1    float64
 197  PP07F1_2    float64
 198  PP07F1_3    float64
 199  PP07I2      float64
 200  PP07I3      float64
 201  PP07I4      float64
 202  PP07L       float64
 203  PP07M       float64
 204  PP08G       float64
 205  PP08G_DSEM  float64
 206  PP08G_DMES  float64
 207  PP08H       float64
 208  PP10B1      float64
 209  PP10B2      float64
 210  PP10B3      float64
 211  PP10B4      float64
 212  PP10B5      float64
 213  PP10B6      float64
 214  PP10B7      float64
 215  PP10B8      float64
 216  PP10B9      float64
 217  PP10B10     float64
 218  PP11L2      float64
 219  V2_01_M     float64
 220  V5_01_M     float64
 221  V5_02_M     float64
 222  V11_01_M    float64
 223  V21_01_M    float64
 224  V21_02_M    int64
 225  V21_03_M    int64
 226  V22_01_M    float64
 227  V22_02_M    float64
 228  V22_03_M    float64
 229  P_DECCF     float64
 230  P_RDECCF    float64
 231  P_GDECCF    float64
 232  P_PDECCF    float64
 233  P_IDECCF    float64
 234  P_ADECCF    float64
dtypes: float64(166), int64(59), object(10)
memory usage: 84.0+ MB

In [ ]:
# Hacemos una limpieza de las variables, nos quedamos con aquellas variables que consideramos relevantes para determinar el modelo.
columns_to_keep = [
    'REGION', 'AGLOMERADO', 'ITF', 'PONDERADOR', 'CH04', 'CH05', 'CH06',
    'CH09', 'CH10', 'CH13', 'CH15_COD', 'NIVEL_ED', 'ESTADO', 'CAT_OCUP',
    'CAT_INAC', 'INTENSI', 'PP05C_1', 'PP05C_2', 'PP05C_3', 'PP04G',
    'PP05H', 'PP06C', 'PP06D', 'PP07C', 'PP07D', 'PP07G_59', 'PP10A',
    'PP10C', 'PP11L', 'ANO4', 'TRIMESTRE'
]

In [ ]:
# Eliminar las columnas que no están en la lista `columns_to_keep`
# Creamos una copia del DataFrame para no modificar el original directamente si no es deseado
df_eph_filtered = df_eph.copy()

# Identificamos las columnas a eliminar
columns_to_drop = [col for col in df_eph_filtered.columns if col not in columns_to_keep]

# Eliminamos las columnas
df_eph_filtered = df_eph_filtered.drop(columns=columns_to_drop)

# Mostrar información del DataFrame resultante para verificar
print(f"Número total de columnas en el DataFrame original: {df_eph.shape[1]}")
print(f"Número de columnas después de la eliminación: {df_eph_filtered.shape[1]}")
print("Primeras 5 filas del DataFrame con columnas seleccionadas:")
print(df_eph_filtered.head())
print("\nColumnas restantes en el DataFrame:")
print(df_eph_filtered.columns.tolist())

Número total de columnas en el DataFrame original: 235
Número de columnas después de la eliminación: 30
Primeras 5 filas del DataFrame con columnas seleccionadas:
   ANO4  TRIMESTRE  REGION  AGLOMERADO  CH04   CH05  CH06  CH09  CH10  CH13  \
0  2024          4      40          29     1  16518    79     1     2     1
1  2024          4      40          29     2  37200    23     1     1     2
2  2024          4      40          29     2  38048    20     1     1     2
3  2024          4      40          29     1  34355    30     1     2     1
4  2024          4      40          29     2  34379    30     1     2     1

   ...  PP05H  PP06C  PP06D  PP07C  PP07D  PP07G_59  PP10A  PP10C  PP11L  \
0  ...    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN    NaN
1  ...    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN    NaN
2  ...    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN    NaN
3  ...    0.0    0.0    0.0    2.0    0.0       0.0    NaN    NaN    NaN
4  ...    0.0    0.0    0.0    2.0    0.0       0.0    NaN    NaN    NaN

         ITF
0  1078000.0
1        0.0
2        0.0
3  1500000.0
4  1500000.0

[5 rows x 30 columns]

Columnas restantes en el DataFrame:
['ANO4', 'TRIMESTRE', 'REGION', 'AGLOMERADO', 'CH04', 'CH05', 'CH06', 'CH09', 'CH10', 'CH13', 'CH15_COD', 'NIVEL_ED', 'ESTADO', 'CAT_OCUP', 'CAT_INAC', 'INTENSI', 'PP04G', 'PP05C_1', 'PP05C_2', 'PP05C_3', 'PP05H', 'PP06C', 'PP06D', 'PP07C', 'PP07D', 'PP07G_59', 'PP10A', 'PP10C', 'PP11L', 'ITF']

In [ ]:
print(" Renombrando columnas a nombres más sencillos...")

nombres_nuevos = {
    'REGION': 'Region',
    'AGLOMERADO': 'Aglomerado',
    'ITF': 'Ingreso_Familiar',
    'PONDERADOR': 'Ponderador',
    'CH04': 'Sexo',
    'CH05': 'Edad',
    'CH06': 'Estado_Civil',
    'CH09': 'Parentesco',
    'CH10': 'Nivel_Educativo_Detalle',
    'CH13': 'Condicion_Actividad_EPH',
    'CH15_COD': 'Pais_Nacimiento',
    'NIVEL_ED': 'Nivel_Educativo_Agrupado',
    'ESTADO': 'Situacion_Actividad_Original',
    'CAT_OCUP': 'Categoria_Ocupacion',
    'CAT_INAC': 'Motivo_Inactividad',
    'INTENSI': 'Intensidad_Ocupacion',
    'PP04G': 'Anios_Experiencia_Laboral',
    'PP05C_1': 'Cantidad_Trabajos',
    'PP05C_2': 'Tareas_Ocupacion',
    'PP05C_3': 'Calificacion_Ocupacion',
    'PP05H': 'Horas_Trabajadas_Semana',
    'PP06C': 'Tipo_Establecimiento',
    'PP06D': 'Sector_Actividad',
    'PP07C': 'Ingreso_Ocupacion_Principal',
    'PP07D': 'Horas_Extras_Principal',
    'PP07H': 'Aportes_Jubilatorios',
    'PP07G_59': 'Obra_Social_Cobertura',
    'PP10A': 'Antiguedad_Puesto_Actual',
    'PP10C': 'Cambio_Puesto_Ultimo_Anio',
    'PP11L': 'Rama_Actividad_CIUO',
    'ANO4': 'Anio_Encuesta',
    'TRIMESTRE': 'Trimestre_Encuesta'
}

df_eph_filtered.rename(columns=nombres_nuevos, inplace=True)

print("\nColumnas renombradas en el DataFrame final:")
print(df_eph_filtered.columns.tolist())
print("\nPrimeras 5 filas del DataFrame 'df_eph_informalidad' final:")
print(df_eph_filtered.head())


print("\nProceso de preparación de datos finalizado.")

 Renombrando columnas a nombres más sencillos...

Columnas renombradas en el DataFrame final:
['Anio_Encuesta', 'Trimestre_Encuesta', 'Region', 'Aglomerado', 'Sexo', 'Edad', 'Estado_Civil', 'Parentesco', 'Nivel_Educativo_Detalle', 'Condicion_Actividad_EPH', 'Pais_Nacimiento', 'Nivel_Educativo_Agrupado', 'Situacion_Actividad_Original', 'Categoria_Ocupacion', 'Motivo_Inactividad', 'Intensidad_Ocupacion', 'Anios_Experiencia_Laboral', 'Cantidad_Trabajos', 'Tareas_Ocupacion', 'Calificacion_Ocupacion', 'Horas_Trabajadas_Semana', 'Tipo_Establecimiento', 'Sector_Actividad', 'Ingreso_Ocupacion_Principal', 'Horas_Extras_Principal', 'Obra_Social_Cobertura', 'Antiguedad_Puesto_Actual', 'Cambio_Puesto_Ultimo_Anio', 'Rama_Actividad_CIUO', 'Ingreso_Familiar']

Primeras 5 filas del DataFrame 'df_eph_informalidad' final:
   Anio_Encuesta  Trimestre_Encuesta  Region  Aglomerado  Sexo   Edad  \
0           2024                   4      40          29     1  16518
1           2024                   4      40          29     2  37200
2           2024                   4      40          29     2  38048
3           2024                   4      40          29     1  34355
4           2024                   4      40          29     2  34379

   Estado_Civil  Parentesco  Nivel_Educativo_Detalle  Condicion_Actividad_EPH  \
0            79           1                        2                        1
1            23           1                        1                        2
2            20           1                        1                        2
3            30           1                        2                        1
4            30           1                        2                        1

   ...  Horas_Trabajadas_Semana  Tipo_Establecimiento  Sector_Actividad  \
0  ...                      NaN                   NaN               NaN
1  ...                      NaN                   NaN               NaN
2  ...                      NaN                   NaN               NaN
3  ...                      0.0                   0.0               0.0
4  ...                      0.0                   0.0               0.0

   Ingreso_Ocupacion_Principal  Horas_Extras_Principal  Obra_Social_Cobertura  \
0                          NaN                     NaN                    NaN
1                          NaN                     NaN                    NaN
2                          NaN                     NaN                    NaN
3                          2.0                     0.0                    0.0
4                          2.0                     0.0                    0.0

   Antiguedad_Puesto_Actual  Cambio_Puesto_Ultimo_Anio  Rama_Actividad_CIUO  \
0                       NaN                        NaN                  NaN
1                       NaN                        NaN                  NaN
2                       NaN                        NaN                  NaN
3                       NaN                        NaN                  NaN
4                       NaN                        NaN                  NaN

   Ingreso_Familiar
0         1078000.0
1               0.0
2               0.0
3         1500000.0
4         1500000.0

[5 rows x 30 columns]

Proceso de preparación de datos finalizado.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46860 entries, 0 to 46859
Columns: 235 entries, CODUSU to P_ADECCF
dtypes: float64(166), int64(59), object(10)
memory usage: 84.0+ MB

In [ ]:
print("Filtrando el DataFrame para mostrar solo los resultados del Gran Buenos Aires...")

# Lista de aglomerados que corresponden al Gran Buenos Aires (incluyendo CABA)
aglomerados_gba = [32, 33]

# Seleccionamos las filas donde la columna 'Aglomerado' esté dentro de nuestra lista aglomerados_gba
df_gba = df_eph_informalidad[df_eph_informalidad['Aglomerado'].isin(aglomerados_gba)].copy()

print(f"\nDataFrame filtrado para Gran Buenos Aires. Filas: {df_gba.shape[0]}, Columnas: {df_gba.shape[1]}")
print("Primeras 5 filas del DataFrame para Gran Buenos Aires:")
print(df_gba.head())
print("\nVerificación de Aglomerados en el nuevo DataFrame (deberían ser solo 32 y 33):")
print(df_gba['Aglomerado'].value_counts(dropna=False))

Filtrando el DataFrame para mostrar solo los resultados del Gran Buenos Aires...

NameError: name 'df_eph_informalidad' is not defined

Conjunto filtrado op